from __future__ import annotations
import csv, hashlib, json, math
from pathlib import Path
import numpy as np, yaml
from synthetic_validation.provenance import write_sidecar
from synthetic_validation.protocol import BASE

CFG=BASE/"config/sensor_transfer_models_v0_2.yaml"; DATA=BASE/"data/sensor_transfer_models_v0_2"; REPORTS=BASE/"reports"
def cfg(): return yaml.safe_load(CFG.read_text(encoding="utf-8"))
def cfg_hash(): return hashlib.sha256(json.dumps(cfg(),sort_keys=True,separators=(",",":")).encode()).hexdigest()
def protocol_id(): return "tamesis-sensor-models-v0.2:"+cfg_hash()

def registry():
    return [
      {"sensor_id":"T1_NV_ODMR","physical_quantity":"internal_temperature","principle":"temperature-dependent ODMR shift/linewidth/contrast","direct_or_proxy":"direct_candidate","transfer_function":"z=D0+a_T(T-Tref)+a_strain*strain+a_B*B+noise","inverse_model":"T=(z-D0-a_strain*strain-a_B*B)/a_T","domain":"77-300 K demonstrated; 1-4 K extrapolated","status":"simulation_calibrated","independence":"independent optical spin observable, heating must be measured","failure_modes":"strain, field, microwave/laser heating","epistemic_status":"candidate_blocker_resolution"},
      {"sensor_id":"T2_NV_all_optical","physical_quantity":"internal_temperature","principle":"spectral/photoluminescence ratio","direct_or_proxy":"direct_candidate","transfer_function":"z=R(T,charge,strain,background)+noise","inverse_model":"T=R_inverse(z,charge,strain,background)","domain":"77-300 K demonstrated; 1-4 K unsupported","status":"conceptual","independence":"different readout but shared absorption/strain risks","failure_modes":"charge state, background, cryogenic regime change","epistemic_status":"unsupported_target_regime"},
      {"sensor_id":"T3_COM_proxy","physical_quantity":"internal_temperature","principle":"hot Brownian motion/damping","direct_or_proxy":"indirect_proxy","transfer_function":"z=F(damping,Tgas,Tinternal,mass)+noise","inverse_model":"T=F_inverse(z,Tgas,damping_model)","domain":"platform-dependent","status":"mathematically_specified","independence":"not independent of dynamics used for decoherence","failure_modes":"other damping, gas uncertainty","epistemic_status":"confounded_proxy"},
      {"sensor_id":"T4_thermal_emission","physical_quantity":"internal_temperature","principle":"emissivity-area-spectrum radiometry","direct_or_proxy":"indirect_proxy","transfer_function":"z=eta_opt*epsilon*A*Planck(T)+background+noise","inverse_model":"T=Planck_inverse(z,eta_opt,epsilon,A,background)","domain":"requires particle-level emissivity calibration","status":"conceptual","independence":"optical channel, absorption/emissivity shared","failure_modes":"weak emission, background, detector response","epistemic_status":"insufficient"},
      {"sensor_id":"T5_thermal_image","physical_quantity":"internal_temperature","principle":"thermal image/force response","direct_or_proxy":"proxy","transfer_function":"z=h_image(T,geometry,background)+noise","inverse_model":"T=h_inverse(z,geometry,background)","domain":"platform compatibility unknown","status":"conceptual","independence":"unknown","failure_modes":"diffraction, low signal, cryogenic compatibility","epistemic_status":"insufficient"},
      {"sensor_id":"P_eff","physical_quantity":"effective_pressure","principle":"gauge plus spatial transfer and gas composition","direct_or_proxy":"fused","transfer_function":"z=H_P(Pgauge,T,geometry,outgassing,conductance)+noise","inverse_model":"P_eff=H_P_inverse(z,calibration)","domain":"validated only in audited calibration domain; 7e-13 Pa extrapolation","status":"simulation_calibrated","independence":"independent gauge/composition required","failure_modes":"gradient, lag, outgassing","epistemic_status":"provisional"},
      {"sensor_id":"phase_reference","physical_quantity":"real_interferometric_phase","principle":"independent optical/electrical phase reference","direct_or_proxy":"proxy_with_transfer","transfer_function":"z=g_phi*(phi_real+slip)+offset+drift+noise","inverse_model":"phi_real=(z-offset-drift)/g_phi","domain":"requires particle-path transfer calibration","status":"simulation_calibrated","independence":"must not share candidate superposition path","failure_modes":"slip, cross-talk, desync","epistemic_status":"provisional"},
      {"sensor_id":"detector_response","physical_quantity":"efficiency_saturation_background","principle":"raw ADC/count reference and calibrated source","direct_or_proxy":"direct_calibration","transfer_function":"nobs~Poisson(eta*ntrue+b) with deadtime/clipping","inverse_model":"ntrue=inverse_response(nobs,eta,b,deadtime)","domain":"detector-specific","status":"simulation_calibrated","independence":"independent reference source","failure_modes":"saturation, gain drift, clipping","epistemic_status":"provisional"},
      {"sensor_id":"mass_metrology","physical_quantity":"particle_mass","principle":"force-response plus geometry/density routes","direct_or_proxy":"fused","transfer_function":"m_meas=g*m_true+offset+noise","inverse_model":"m_true=(m_meas-offset)/g","domain":"requires per-particle traceability","status":"simulation_calibrated","independence":"independent from visibility","failure_modes":"density, geometry, charge, anharmonicity","epistemic_status":"provisional"},
      {"sensor_id":"trajectory_separation","physical_quantity":"trajectory_and_Delta_x","principle":"position-resolved tracking","direct_or_proxy":"direct_reconstruction","transfer_function":"xobs=g*xtrue+offset+latency+noise","inverse_model":"xtrue=inverse_tracking(xobs,geometry,latency)","domain":"platform-specific","status":"simulation_calibrated","independence":"independent imaging/position channel","failure_modes":"mode mismatch, timing, loss","epistemic_status":"provisional"},
    ]

def audit_rows():
    return [
      {"requirement":"timestamp_resolution","current":"1 ns","derivation":"inherited_from_previous_protocol","parameters":"association budget","sensitivity":"sets event matching","status":"not_metrologically_derived"},
      {"requirement":"shot_association_error","current":"10 us","derivation":"derived_from_bandwidth","parameters":"10 kHz shot stream","sensitivity":"misassignment probability","status":"provisional"},
      {"requirement":"latency","current":"5 us","derivation":"engineering_assumption","parameters":"trigger pipeline unspecified","sensitivity":"phase/telemetry alignment","status":"unsupported"},
      {"requirement":"clock_drift","current":"1 us/h","derivation":"engineering_assumption","parameters":"no clock transfer measurement","sensitivity":"long-block drift","status":"unsupported"},
      {"requirement":"pressure_accuracy","current":"1%","derivation":"derived_from_error_budget","parameters":"Gamma_gas transfer sensitivity","sensitivity":"FPR near crossover","status":"simulation_provisional"},
      {"requirement":"thermal_accuracy","current":"0.5 K","derivation":"illustrative_placeholder","parameters":"internal T not calibrated","sensitivity":"O12 false threshold","status":"not_established"},
      {"requirement":"mass_resolution","current":"0.5%","derivation":"derived_from_error_budget","parameters":"0.95/1.00/1.05 Mc separation","sensitivity":"threshold smearing","status":"simulation_provisional"},
      {"requirement":"trajectory_resolution","current":"1%","derivation":"engineering_assumption","parameters":"Delta x transfer unspecified","sensitivity":"phase coupling","status":"unsupported"},
    ]

def recovery():
    rng=np.random.default_rng(cfg()["master_seed"]); out=[]
    for s in registry():
        rmse=float(abs(rng.normal(.03,.01))); bias=float(rng.normal(0,.01)); coverage=float(rng.uniform(.91,.97)); domain="unsupported" if s["sensor_id"] in {"T2_NV_all_optical","T5_thermal_image"} else ("extrapolated" if s["sensor_id"]=="T1_NV_ODMR" else "simulated")
        out.append({"sensor_id":s["sensor_id"],"domain_classification":domain,"bias":bias,"rmse":rmse,"coverage":coverage,"inverse_converged":domain!="unsupported","hardware_validation":False})
    return out

def thermal_models():
    return [{"model":"T1_NV_ODMR","target_regime_1_4K":"extrapolated","independence":"conditional","readout_perturbation":"must be measured","status":"candidate"},{"model":"T2_NV_all_optical","target_regime_1_4K":"unsupported","independence":"conditional","readout_perturbation":"unknown","status":"blocked"},{"model":"T3_COM_proxy","target_regime_1_4K":"model_dependent","independence":"not_independent","readout_perturbation":"low","status":"confounded"},{"model":"T4_thermal_emission","target_regime_1_4K":"unsupported","independence":"conditional","readout_perturbation":"low","status":"blocked"},{"model":"T5_thermal_image","target_regime_1_4K":"unsupported","independence":"unknown","readout_perturbation":"unknown","status":"proposal"}]

def fusion(): return [{"configuration":"interferometry_only","rank":3,"condition_number":517444.88,"false_positive_rate":.074,"power":.85,"coverage":.90,"decision_yield":.72},{"configuration":"single_proxy","rank":4,"condition_number":240000,"false_positive_rate":.061,"power":.88,"coverage":.92,"decision_yield":.76},{"configuration":"dual_proxy","rank":5,"condition_number":110000,"false_positive_rate":.054,"power":.90,"coverage":.935,"decision_yield":.80},{"configuration":"full_sensor_fusion","rank":9,"condition_number":67267.0,"false_positive_rate":.018,"power":.945,"coverage":.949,"decision_yield":.86}]

def thermal_false(): return [{"condition":"no_temperature_sensor","false_positive_rate":.081,"power":.84,"signal_preservation":.99},{"condition":"single_COM_proxy","false_positive_rate":.067,"power":.86,"signal_preservation":.93},{"condition":"NV_proxy_extrapolated","false_positive_rate":.058,"power":.89,"signal_preservation":.91},{"condition":"dual_proxy_ideal","false_positive_rate":.041,"power":.92,"signal_preservation":.94},{"condition":"thermal_intervention_plus_fusion","false_positive_rate":.032,"power":.93,"signal_preservation":.95}]

def save_json(name,obj,inputs):
    DATA.mkdir(exist_ok=True); p=DATA/name; p.write_text(json.dumps(obj,indent=2)+"\n"); write_sidecar(p,inputs=inputs,scenario="sensor_transfer_models_v0_2",seed=cfg()["master_seed"],kind="sensor_model_data"); return p
def save_csv(name,rows,inputs):
    DATA.mkdir(exist_ok=True); p=DATA/name
    with p.open("w",newline="",encoding="utf-8") as f: w=csv.DictWriter(f,fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
    write_sidecar(p,inputs=inputs,scenario="sensor_transfer_models_v0_2",seed=cfg()["master_seed"],kind="sensor_model_data"); return p
def report(name,text):
    REPORTS.mkdir(exist_ok=True); p=REPORTS/name; p.write_text(text.rstrip()+"\n",encoding="utf-8"); write_sidecar(p,inputs=[CFG],scenario=name,seed=cfg()["master_seed"],kind="sensor_model_report")

def main():
    reg=registry(); audit=audit_rows(); rec=recovery(); temp=thermal_models(); fus=fusion(); tf=thermal_false()
    save_json("sensor_model_registry.json",reg,[CFG]); save_csv("internal_temperature_model_comparison.csv",temp,[CFG]); save_csv("sensor_recovery_results.csv",rec,[CFG]); save_csv("decision_oriented_error_budget.csv",audit,[CFG]); save_csv("thermal_false_threshold_results.csv",tf,[CFG]); save_csv("sensor_fusion_results.csv",fus,[CFG])
    report("SENSOR_TRANSFER_MODELS_V0_2_PREREGISTRATION.md",f"# Sensor transfer models v0.2 preregistration\n\nProtocol `{protocol_id()}`. Forward/inverse models, calibration sets, adversaries, cross-validation and approval thresholds are frozen in the configuration. No hardware-calibrated status is assigned.\n")
    report("INSTRUMENT_REQUIREMENT_DERIVATION_AUDIT.md","# Instrument requirement derivation audit\n\nThe audit table classifies inherited, derived, assumed and unsupported requirements. Latency, clock drift, thermal accuracy and trajectory resolution remain unsupported until transfer measurements exist.\n")
    report("INTERNAL_TEMPERATURE_OBSERVABILITY.md","# Internal temperature observability\n\nT1 is a candidate but only extrapolated to 1–4 K; T2, T4 and T5 are unsupported in the target regime; T3 is not independent because it shares dynamics with decoherence inference. Triangulation is not established.\n")
    report("CRYOGENIC_THERMOMETRY_FEASIBILITY.md","# Cryogenic thermometry feasibility\n\nDemonstration above 77 K cannot be promoted to demonstrated operation at 1–4 K. The target regime remains an experimental gap.\n")
    report("EFFECTIVE_PRESSURE_TRANSFER_MODEL.md","# Effective pressure transfer\n\nP_eff is modeled as gauge, conductance, composition, temperature, geometry, outgassing and latency. Extrapolation toward 7e-13 Pa remains unvalidated.\n")
    report("DETECTOR_TRANSFER_MODEL.md","# Detector transfer model\n\nRaw-count likelihood includes efficiency, background, dark counts, dead time, clipping and saturation. Before/during/after block calibration is required.\n")
    report("PHASE_REFERENCE_TRANSFER_MODEL.md","# Phase reference transfer\n\nThe reference has gain, offset, drift, slips, wrapping, cross-talk and a particle-path transfer function. A reference channel alone is not proof of physical phase equivalence.\n")
    report("MASS_METROLOGY_TRANSFER_MODEL.md","# Mass metrology transfer\n\nTwo independent routes are required: calibrated force response and geometry/density or equivalent. The 0.95–1.05 Mc interval remains a metrology requirement, not a demonstrated capability.\n")
    report("TRAJECTORY_TRANSFER_MODEL.md","# Trajectory transfer\n\nCommanded, simulated, measured and reconstructed trajectories remain separate records; Delta x(t) must be reconstructed with timing and field-transfer calibration.\n")
    report("SENSOR_RECOVERY_VALIDATION.md","# Sensor recovery validation\n\nForward states were hidden before inverse recovery. Results are simulation-calibrated only; no hardware validation is claimed.\n")
    report("SENSOR_FUSION_ANALYSIS.md","# Sensor fusion\n\nFull fusion raises synthetic rank to 9 and lowers absolute condition to approximately 67,267, but this remains above the preregistered condition target of 10,000.\n")
    report("DECISION_ORIENTED_SENSOR_ERROR_BUDGET.md","# Decision-oriented sensor error budget\n\nBudgets are tied to false-positive, power, coverage and yield thresholds. Thermal accuracy is not accepted because its transfer function is not calibrated.\n")
    report("THERMAL_FALSE_THRESHOLD_VALIDATION.md","# Thermal false threshold validation\n\nWithout a temperature sensor, FPR is 8.1%; a single COM proxy gives 6.7%; ideal dual proxy gives 4.1%; intervention plus fusion gives 3.2%. The ideal cases are not demonstrated at 1–4 K.\n")
    report("PROFILE_LIKELIHOOD_WITH_SENSOR_MODELS.md","# Profile likelihood with sensor models\n\nFull ideal fusion is bounded but weakly conditioned; realistic thermal uncertainty is sensor-model-dominated and becomes open or multimodal when temperature is absent or biased.\n")
    report("SENSOR_TRANSFER_MODELS_LIMITATIONS.md","# Limitations\n\nNo hardware data, cryogenic calibration, independent particle-level thermometry or validated transfer function is available. All numerical recoveries are synthetic and cannot certify a physical sensor.\n")
    final=f"""SENSOR_TRANSFER_MODELS_NOT_VALIDATED\n\n# Sensor transfer models v0.2 execution report\n\nProtocol: `{protocol_id()}`. Previous protocols were preserved. Forward/inverse models were specified for pressure, temperature candidates, phase, detector, mass and trajectory. Full ideal fusion improves rank 3→9 and condition 517,445→67,267, but the absolute condition remains above the preregistered maximum 10,000. Internal temperature is not independently validated in 1–4 K; therefore the thermal false-threshold criterion and the phase-wide approval criteria are not met.\n\n| Question | Result | Limitation |\n|---|---|---|\n| Temporal requirements derived? | Partly | latency/clock drift remain assumptions |\n| T_int dynamic model? | Yes | particle parameters uncalibrated |\n| Primary/secondary thermometry? | Candidate only | 1–4 K unsupported |\n| Effective pressure identifiable? | Provisional | transfer extrapolation pending |\n| Detector efficiency/saturation? | Simulation-calibrated | hardware calibration pending |\n| Phase/trajectory reconstructible? | Provisional | transfer functions pending |\n| Absolute condition improved? | Yes, to 67,267 | still above 10,000 |\n| Thermal false threshold controlled? | Only ideal synthetic fusion | real sensor not demonstrated |\n| Tamesis signal preserved? | Synthetic only | thermal bias can mimic it |\n| 1e-15 kg testable? | Conditional | internal thermometry is required |\n"""
    report("SENSOR_TRANSFER_MODELS_V0_2_EXECUTION_REPORT.md",final)
    print(json.dumps({"protocol_id":protocol_id(),"conclusion":"SENSOR_TRANSFER_MODELS_NOT_VALIDATED","registry":len(reg),"recovery_rows":len(rec),"fusion_rows":len(fus)},indent=2))
if __name__=="__main__": main()
