import TamesisLab.Foundations.Basic
import TamesisLab.Foundations.Semigroups
import TamesisLab.Foundations.FiniteDynamics
import TamesisLab.Foundations.FunctionalGraphs
import TamesisLab.Foundations.CycleDetection
import TamesisLab.Foundations.CycleDetection.Audit
import TamesisLab.Foundations.FiniteStateAbstraction
import TamesisLab.Foundations.FiniteStateAbstraction.Audit
import TamesisLab.Foundations.BisimulationBoundary
import TamesisLab.Foundations.Invariants
import TamesisLab.Foundations.Monovariants
import TamesisLab.Foundations.Descent
import TamesisLab.Foundations.ComputabilityBridge
import TamesisLab.Foundations.UniformPrimrec
import TamesisLab.Foundations.SpectralCounting
import TamesisLab.Foundations.FourierMultiplierL2
import TamesisLab.Foundations.EllipticHeight
import TamesisLab.Foundations.LerayProjector
import TamesisLab.Foundations.SobolevSpace
import TamesisLab.Foundations.SpectralCountingInstance
import TamesisLab.Foundations.LerayOrthogonal
import TamesisLab.Foundations.Helmholtz
import TamesisLab.Foundations.LerayProjectorSobolev
import TamesisLab.Foundations.LerayOrthogonalSobolev
import TamesisLab.Foundations.HeatSemigroup
import TamesisLab.Foundations.DuhamelSkeleton
import TamesisLab.Foundations.BisimulationBoundary.Audit

namespace TamesisLab.Foundations

theorem foundations_smoke : True := by
  trivial

end TamesisLab.Foundations
