"""
Independent KS test: compare my from-scratch per-shape continuum MC
samples (persh_samples.npz, generated by an independent implementation)
against the EXACT closed-form conditional densities f_shape(x)/P_shape
that ATTEMPT.md reports, computed here via sympy from the formulas as
TRANSCRIBED from the document's prose (not from its code).
"""
import numpy as np
import sympy as sp
from scipy import stats

x = sp.symbols('x', positive=True)

# Formulas as reported in ATTEMPT.md section 4 (transcribed from the
# document's prose table, not from any of its scripts):
f_T1a = 3*x*(x-1)**2*(2*x+1)
f_T1b = sp.Rational(3,2)*x**2*(x-1)**2*(x+2)
f_T1c = x**3*(x-1)**2
f_T2a = sp.Rational(3,2)*x**2*(x-1)**2*(x+2)
f_T2b = sp.Rational(3,2)*x**3*(x-1)**2
f_T3  = sp.Rational(1,2)*x**3*(x-1)**2
f_T0  = 3*x**3 - 6*x**2 + 3*x

formulas = {'T0': f_T0, 'T1a': f_T1a, 'T1b': f_T1b, 'T1c': f_T1c,
            'T2a': f_T2a, 'T2b': f_T2b, 'T3': f_T3}

expected_p = {'T1a': sp.Rational(9,20), 'T1b': sp.Rational(1,8), 'T1c': sp.Rational(1,60),
              'T2a': sp.Rational(1,8), 'T2b': sp.Rational(1,40), 'T3': sp.Rational(1,120),
              'T0': sp.Rational(1,4)}

print("Sanity: integral of each f_shape over (0,1) should equal its target probability:")
for k, f in formulas.items():
    I = sp.integrate(f, (x, 0, 1))
    print(f"  {k}: integral(f_{k})={I}  target P={expected_p[k]}  match={sp.simplify(I-expected_p[k])==0}")

print("\nSum of all 7 densities, compare to 6x(1-x^2)^2:")
total = sp.expand(sum(formulas.values()))
target = sp.expand(6*x*(1-x**2)**2)
print(" total  =", total)
print(" target =", target)
print(" diff simplifies to:", sp.simplify(total - target))

# Build exact CDFs of the CONDITIONAL density f_shape(x)/P_shape (so it
# integrates to 1) as a python-callable via sympy lambdify, and KS-test
# against my independent MC samples for each shape.
data = np.load('/tmp/claude-0/-home-user-TamesisTheoryCompleteResearchArchive/e9ab1ff0-e9f9-5b73-816d-aec417acf7b1/scratchpad/persh_samples.npz')

print("\n" + "="*70)
print("KS tests: independent MC samples (per shape) vs document's closed-form conditional density")
print("="*70)
for k in ['T0','T1a','T1b','T1c','T2a','T2b','T3']:
    f = formulas[k]
    P = expected_p[k]
    cdf_expr = sp.integrate(f, (x, 0, x)) / P
    cdf_func = sp.lambdify(x, cdf_expr, 'numpy')
    samples = data[k]
    D, p = stats.kstest(samples, cdf_func)
    mean_emp = samples.mean()
    mean_exact = sp.nsimplify(sp.integrate(x*f, (x,0,1))/P)
    print(f"  {k}: n={len(samples):8d}  KS D={D:.5f}  p={p:.4f}   mean_emp={mean_emp:.6f}  mean_exact={float(mean_exact):.6f}")
