/-
  QF-10 -- Packaging the Heisenberg flow `t ↦ exp (t • heisenbergGenerator)`
  as a `MonoidHom (Multiplicative ℝ) →* unitary (Matrix (Fin 2) (Fin 2) ℂ)`.
  Direct extension of Wave-4 batch item WAVE4-QF-7
  (`HeisenbergFlowUnitarity.lean`, this directory, unitarity of the flow)
  and Wave-5 batch item WAVE5-QF-9 (`HeisenbergFlowGroupLaw.lean`, this
  directory, the bare pointwise addition law `heisenbergFlow_add`).
  Sibling also of WAVE2-QF-5 (`HeisenbergCommutatorFlowIdentity.lean`),
  WAVE3-QF-6 (`EhrenfestExpectationValueIdentity.lean`), and WAVE5-QF-8
  (`HeisenbergFlowNormPreservation.lean`), this directory. Wave-6 batch
  item WAVE6-QF-10.

  STATUS: drafted and self-checked with `lake env lean` by the authoring
  session (single-file typecheck against the existing built Mathlib
  cache, NOT a full `lake build` -- see the Wave-6 task instructions on
  build contention with 13 concurrent sibling agents). Not registered in
  `TamesisLab.lean`; free-standing, following the precedent of every
  other file in this directory, none of which import each other -- only
  Mathlib. Consistent with that precedent, this file does NOT `import`
  `HeisenbergFlowUnitarity.lean` / `HeisenbergFlowGroupLaw.lean` as Lean
  modules; instead it re-declares the identical `heisenbergGenerator`
  definition and re-derives both the unitarity fact (QF-7) and the
  addition law (QF-9) locally (see below), citing their QF-4/QF-7/QF-9
  origin.

  HONESTY NOTE (mandatory, per `../SCOPE.md` in this directory's parent).
  "Quantum-Classical Unification" (QCU-001) is a lab-internal extension,
  informally numbered "Problem 8", added at explicit user request. It is
  **not** one of the seven Clay Millennium Problems, has no official
  recognition, no $1,000,000 prize, and no single agreed formal
  statement. This file makes ZERO claim that any Millennium problem
  (Clay-official or otherwise) is solved, approximated, or reachable,
  and ZERO claim of mathematical novelty: that a one-parameter flow
  `t ↦ exp(tH)` generated by a fixed skew-adjoint element `H` assembles
  into a group homomorphism `(ℝ, +) → U` (equivalently, a `MonoidHom`
  out of `Multiplicative ℝ`) is one of the most standard facts in
  operator theory, assembled here PURELY by re-packaging three already-
  closed pointwise facts (QF-7's unitarity, QF-9's addition law, and the
  generic `MonoidHom.mk'` constructor) into one bundled algebraic object
  -- no new mathematical content beyond that packaging step.

  MOTIVATION / WHAT THIS FILE DOES, exactly as scoped by the Wave-6
  plan. QF-7 proved `exp (t • heisenbergGenerator) ∈ unitary (Matrix
  (Fin 2) (Fin 2) ℂ)` for every `t : ℝ`. QF-9 proved the bare pointwise
  addition law `exp ((s + t) • heisenbergGenerator) = exp (s •
  heisenbergGenerator) * exp (t • heisenbergGenerator)` for every
  `s t : ℝ`, explicitly flagging in its own "WHAT IS STILL MISSING"
  item (a) that it does NOT bundle this into a `MonoidHom` or similar.
  This file closes exactly that one gap: it assembles QF-7's unitarity
  and QF-9's addition law into a single bundled
  `heisenbergFlowHom : Multiplicative ℝ →* unitary (Matrix (Fin 2)
  (Fin 2) ℂ)`, via the prescribed method:
    (a) `toFun := fun t => ⟨exp (t.toAdd • heisenbergGenerator),
        exp_heisenbergFlow_mem_unitary t.toAdd⟩ : unitary (Matrix
        (Fin 2) (Fin 2) ℂ)`, i.e. the flow value paired with its QF-7
        unitarity proof, packaged as an element of the `unitary`
        submonoid/subtype;
    (b) `map_mul'` via `toAdd_mul` (`(a * b).toAdd =
        a.toAdd + b.toAdd`, a `rfl` lemma) followed by `heisenbergFlow_add`
        (QF-9, re-derived locally -- see the SCOPE ANSWER below for
        under which norm scope);
    (c) `MonoidHom.mk'` (`Mathlib/Algebra/Group/Hom/Defs.lean:589`),
        which needs only `[MulOneClass M] [Group G]` and derives
        `map_one'` automatically via `mul_right_cancel_iff` -- fed by
        `Multiplicative.instGroup` (`M := Multiplicative ℝ`, since `ℝ`
        is an additive group) and `unitary.instGroup`
        (`Mathlib/Algebra/Star/Unitary.lean:96`, `G := unitary (Matrix
        (Fin 2) (Fin 2) ℂ)`), neither of which depends on any norm/
        topology scope -- the `Group (unitary R)` instance is purely
        algebraic (`[Monoid R] [StarMul R]` only), so no diamond risk
        exists at this step regardless of which scope is open elsewhere
        in the file.
  RESULT: closes with ZERO friction beyond re-deriving QF-7's and QF-9's
  own pointwise facts (both reused, not re-invented). The one risk this
  candidate's own falsifiable-test description flagged explicitly --
  "reportar sob qual escopo (Operator ou L2Operator) de fato fechou" --
  is answered here: **`Matrix.Norms.L2Operator` is the scope that
  actually closes this file.** This differs from QF-9's own answer
  (`Matrix.Norms.Operator`, "the simpler of the two scopes"), because
  this file additionally needs QF-7's unitarity fact
  (`exp_heisenbergFlow_mem_unitary`) to typecheck `toFun`, and QF-7
  documents in detail (its own "UNANTICIPATED FRICTION POINT" section)
  that unitarity genuinely requires `ContinuousStar`, which only the
  `Matrix.Norms.L2Operator` scope supplies without a topology diamond.
  Since only ONE scope may be open at a time without risking a duplicate-
  instance diamond on `NormedRing (Matrix (Fin 2) (Fin 2) ℂ)`, this file
  opens `Matrix.Norms.L2Operator` only (matching QF-7/QF-8, not QF-9),
  and RE-DERIVES QF-9's addition law under that scope rather than the
  `Matrix.Norms.Operator` scope QF-9 itself used. This re-derivation was
  the one genuine open question anticipated by the Wave-6 plan text
  ("re-derivar a lei de adicao de QF-9 sob Matrix.Norms.L2Operator em
  vez de Matrix.Norms.Operator"), and it goes through with ZERO
  friction: `NormedSpace.exp_add_of_commute`
  (`Mathlib/Analysis/Normed/Algebra/Exponential.lean:520`) needs only
  the `[NormedRing 𝔸] [NormedAlgebra ℚ 𝔸] [CompleteSpace 𝔸]` instances
  from the algebra's "Rat" section, with no `star`/`ContinuousStar`
  dependency anywhere in that chain -- and `Matrix.instL2OpNormedRing` /
  `Matrix.instL2OpNormedAlgebra` (`Mathlib/Analysis/CStarAlgebra/
  Matrix.lean:264,270`, both scoped under `Matrix.Norms.L2Operator`)
  supply exactly `NormedRing` / `NormedAlgebra ℂ` under this scope, with
  `CompleteSpace` and `NormedAlgebra ℚ` obtained exactly as QF-7/QF-9
  each already obtain them (finite-dimensionality, resp.
  `NormedAlgebra.restrictScalars ℚ ℂ`). The `Commute (s •
  heisenbergGenerator) (t • heisenbergGenerator)` fact itself
  (`Commute.refl`/`.smul_right`/`.smul_left`) is purely algebraic
  (`Matrix.instAlgebra`), independent of any norm scope, exactly as
  QF-9's own header already notes.

  MATHLIB TOOLS USED (verified present by direct read of the vendored
  snapshot at `04_FORMAL_RESEARCH_LAB/05_FORMAL/lean/.lake/packages/mathlib`,
  in addition to compiling cleanly via `lake env lean`):
    - `skewAdjoint.smul_mem`, `exp_mem_unitary_of_mem_skewAdjoint`,
      `NormedAlgebra.restrictScalars`, and the `Matrix.Norms.L2Operator`
      scoped instance chain (`Matrix.instCStarRing`,
      `Matrix.instL2OpNormedRing`, `Matrix.instL2OpNormedAlgebra`) --
      all reused verbatim from QF-7 (`HeisenbergFlowUnitarity.lean`,
      this directory; see that file's header for the full citation
      trail of each, including the `ContinuousStar` friction-point
      report).
    - `add_smul`, `Commute.refl`, `Commute.smul_right`,
      `Commute.smul_left`, `NormedSpace.exp_add_of_commute`
      (`Mathlib/Analysis/Normed/Algebra/Exponential.lean:520`) -- all
      reused from QF-9 (`HeisenbergFlowGroupLaw.lean`, this directory),
      re-instantiated here under the `Matrix.Norms.L2Operator` scope
      (rather than QF-9's own `Matrix.Norms.Operator` scope) as
      documented above.
    - `Multiplicative`, `Multiplicative.toAdd`, `toAdd_mul`
      (`Mathlib/Algebra/Group/TypeTags/Basic.lean:87,163`, the latter a
      top-level (not `Multiplicative`-namespaced) `rfl` lemma:
      `(x * y).toAdd = x.toAdd + y.toAdd`), and the
      `Group (Multiplicative ℝ)` instance transported from `AddGroup ℝ`.
    - `unitary` (`Mathlib/Algebra/Star/Unitary.lean:33`, the
      `Submonoid` of star-unitary elements) and its `Group (unitary R)`
      instance (`Mathlib/Algebra/Star/Unitary.lean:96`, `inv := star,
      inv_mul_cancel := star_mul_self`), unconditional on `[Monoid R]
      [StarMul R]`.
    - `MonoidHom.mk'` (`Mathlib/Algebra/Group/Hom/Defs.lean:589`)
      `[MulOneClass M] [Group G] (f : M → G) (map_mul : ∀ a b, f (a * b)
      = f a * f b) : M →* G`, with `map_one'` derived automatically via
      `mul_right_cancel_iff`, instantiated at `M := Multiplicative ℝ`,
      `G := unitary (Matrix (Fin 2) (Fin 2) ℂ)`.

  WHAT THIS FILE DOES / THE FALSIFIABLE TEST, exactly as specified. Fix
  the same `2 × 2` skew-Hermitian generator `heisenbergGenerator =
  diag(i, -i)` as QF-4/.../QF-9. Construct
  `heisenbergFlowHom : Multiplicative ℝ →* unitary (Matrix (Fin 2)
  (Fin 2) ℂ)` via `MonoidHom.mk'`, with `toFun := fun t => ⟨exp
  (t.toAdd • heisenbergGenerator), (QF-7 unitarity)⟩` and `map_mul'` via
  `toAdd_mul` + `heisenbergFlow_add` (QF-9), exactly as the falisfiable
  test prescribes. **SCOPE ANSWER (as requested by the plan):
  `Matrix.Norms.L2Operator` is the scope that actually closed this
  file** -- it is opened once, and QF-9's addition law is re-derived
  under it (rather than reusing QF-9's own `Matrix.Norms.Operator`
  scope), to avoid a duplicate-instance diamond with QF-7's unitarity
  requirement, which is not optional here (see "RESULT" above for the
  full reasoning).

  WHAT IS STILL MISSING even on full success of this file (stated
  honestly, per the Wave-6 instructions, mirroring QF-4/.../QF-9's own
  honesty sections). This file proves ONLY that the map `t ↦ exp (t •
  heisenbergGenerator)` assembles into a bundled `MonoidHom` from
  `Multiplicative ℝ` into the (purely algebraic, discrete) group
  `unitary (Matrix (Fin 2) (Fin 2) ℂ)`. It does **not**: (a) prove any
  continuity of `heisenbergFlowHom` or upgrade it to a
  `ContinuousMonoidHom` / one-parameter group in the topological sense
  -- that is the separate, explicitly-gated concern of the sibling
  candidate QF-11 in this same Wave-6 batch, not attempted here; (b)
  prove any Ehrenfest theorem, Schrödinger/Heisenberg equation of
  motion, or correspondence-principle statement -- those are the
  separate concerns of QF-5/QF-6 in this same directory; (c) extend to
  `t : ℂ` (shown false in general in QF-7's header) or to any
  unbounded/physical position-momentum generator (per QF-2/QF-3 in this
  same directory, this bounded/finite-dimensional setting cannot even
  realize the canonical commutation relation, so `heisenbergGenerator`
  is explicitly NOT a physical Hamiltonian); (d) connect to QF-8's
  norm/inner-product preservation results -- this file's bundled object
  lives entirely in the abstract `unitary (Matrix (Fin 2) (Fin 2) ℂ)`
  group, with no reference to `EuclideanSpace` or `toEuclideanCLM`; (e)
  prove injectivity, surjectivity, or any other structural property of
  `heisenbergFlowHom` beyond it being a well-defined group
  homomorphism; (f) connect to any `ħ → 0` classical limit or any
  physical interpretation of the bundled homomorphism beyond the bare
  algebraic packaging.
-/
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.Algebra.Star.Module
import Mathlib.Analysis.RCLike.Basic
import Mathlib.Algebra.Star.Unitary
import Mathlib.Algebra.Group.TypeTags.Basic

open scoped Matrix.Norms.L2Operator
open NormedSpace

namespace QF10.HeisenbergFlowMonoidHom

/-- The fixed generator for this probe, identical to QF-4's/.../QF-9's
`heisenbergGenerator`: `H = diag(i, -i)`, a concrete `2 × 2`
skew-Hermitian complex matrix. Re-declared locally rather than imported,
per this directory's established free-standing-file precedent (see the
header note above). Playing the role of a toy "Hamiltonian-like"
generator for the purposes of this single-identity feasibility test; NOT
claimed to be a physical Hamiltonian (real position/momentum generators
are unbounded, per QF-2 / QF-3 in this same directory). -/
noncomputable def heisenbergGenerator : Matrix (Fin 2) (Fin 2) ℂ :=
  !![Complex.I, 0; 0, -Complex.I]

/-- **Skew-adjoint membership**, identical to QF-7's/QF-8's/QF-9's
`heisenbergGenerator_mem_skewAdjoint`: `heisenbergGenerator ∈
skewAdjoint (Matrix (Fin 2) (Fin 2) ℂ)`, i.e. `star heisenbergGenerator
= -heisenbergGenerator`, proved by the same concrete entrywise
computation QF-4/QF-7/QF-8 use. -/
theorem heisenbergGenerator_mem_skewAdjoint :
    heisenbergGenerator ∈ skewAdjoint (Matrix (Fin 2) (Fin 2) ℂ) := by
  rw [skewAdjoint.mem_iff, Matrix.star_eq_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [heisenbergGenerator, Matrix.conjTranspose_apply]

/-- **Scalar skew-adjointness**, identical to QF-7's/QF-8's
`smul_heisenbergGenerator_mem_skewAdjoint`: `t • heisenbergGenerator ∈
skewAdjoint (Matrix (Fin 2) (Fin 2) ℂ)` for every `t : ℝ`, via
`skewAdjoint.smul_mem`. See QF-7's header for the full instance-chain
citation (`TrivialStar ℝ`, `StarModule ℝ (Matrix (Fin 2) (Fin 2) ℂ)`). -/
theorem smul_heisenbergGenerator_mem_skewAdjoint (t : ℝ) :
    t • heisenbergGenerator ∈ skewAdjoint (Matrix (Fin 2) (Fin 2) ℂ) :=
  skewAdjoint.smul_mem t heisenbergGenerator_mem_skewAdjoint

/-- **QF-7's unitarity result, re-derived locally.** The Heisenberg flow
`exp (t • heisenbergGenerator)` is unitary in `Matrix (Fin 2) (Fin 2)
ℂ` for every real time `t : ℝ`. Identical statement and proof to QF-7's
`exp_heisenbergFlow_mem_unitary` (`HeisenbergFlowUnitarity.lean`, this
directory); see that file's header for the full friction-point report
on why the `Matrix.Norms.L2Operator` scope (rather than
`Matrix.Norms.Operator`) is needed. -/
theorem exp_heisenbergFlow_mem_unitary (t : ℝ) :
    exp (t • heisenbergGenerator) ∈ unitary (Matrix (Fin 2) (Fin 2) ℂ) :=
  haveI : NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ) :=
    NormedAlgebra.restrictScalars ℚ ℂ (Matrix (Fin 2) (Fin 2) ℂ)
  exp_mem_unitary_of_mem_skewAdjoint (smul_heisenbergGenerator_mem_skewAdjoint t)

/-- **QF-9's addition law, re-derived locally under `Matrix.Norms.L2Operator`
(NOT QF-9's own `Matrix.Norms.Operator` scope -- see the file header's
"RESULT" section for why only one scope can be open here without a
duplicate-instance diamond, and why this file needs the `L2Operator`
one for `exp_heisenbergFlow_mem_unitary` above).** The Heisenberg flow
`t ↦ exp (t • heisenbergGenerator)` satisfies the one-parameter-group
addition law: `exp ((s + t) • heisenbergGenerator) = exp (s •
heisenbergGenerator) * exp (t • heisenbergGenerator)` for every
`s t : ℝ`. This re-derivation under the `L2Operator` scope is the one
genuine open question this file's falsifiable test carried in; it
closes with ZERO friction, since `NormedSpace.exp_add_of_commute`
needs no `star`-compatibility instance at all (only `[NormedRing]
[NormedAlgebra ℚ] [CompleteSpace]`, all supplied under `L2Operator`
exactly as under `Operator`). -/
theorem heisenbergFlow_add (s t : ℝ) :
    exp ((s + t) • heisenbergGenerator) =
      exp (s • heisenbergGenerator) * exp (t • heisenbergGenerator) := by
  haveI : NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ) :=
    NormedAlgebra.restrictScalars ℚ ℂ (Matrix (Fin 2) (Fin 2) ℂ)
  rw [add_smul]
  exact exp_add_of_commute
    (((Commute.refl heisenbergGenerator).smul_right t).smul_left s)

/-- **Main result (QF-10), the falsifiable test exactly as specified.**
The Heisenberg flow `t ↦ exp (t • heisenbergGenerator)`, packaged as a
function `Multiplicative ℝ → unitary (Matrix (Fin 2) (Fin 2) ℂ)`
(pairing each flow value with its QF-7 unitarity witness), assembles
into a bundled `MonoidHom`, via `MonoidHom.mk'` fed by `toAdd_mul`
(a `rfl` fact about `Multiplicative`) and `heisenbergFlow_add` above.
Closes under the `Matrix.Norms.L2Operator` scope -- see the file
header's "SCOPE ANSWER" for the full reasoning on why this scope
(rather than QF-9's `Matrix.Norms.Operator`) is the one that actually
closes this file. -/
noncomputable def heisenbergFlowHom :
    Multiplicative ℝ →* unitary (Matrix (Fin 2) (Fin 2) ℂ) :=
  MonoidHom.mk'
    (fun t => ⟨exp (t.toAdd • heisenbergGenerator),
      exp_heisenbergFlow_mem_unitary t.toAdd⟩)
    (fun a b => by
      apply Subtype.ext
      show exp ((a * b).toAdd • heisenbergGenerator) =
          exp (a.toAdd • heisenbergGenerator) * exp (b.toAdd • heisenbergGenerator)
      rw [toAdd_mul]
      exact heisenbergFlow_add a.toAdd b.toAdd)

/-- **Sanity-check corollary**, immediate from `heisenbergFlowHom`'s
bundled `MonoidHom` structure: the underlying matrix of the packaged
homomorphism at `Multiplicative.ofAdd t` is exactly the flow value
`exp (t • heisenbergGenerator)`, confirming the packaging did not
silently change the underlying object. Not part of the falsifiable
test itself; included only as an explicit unfolding check. -/
theorem coe_heisenbergFlowHom_apply (t : ℝ) :
    (heisenbergFlowHom (Multiplicative.ofAdd t) : Matrix (Fin 2) (Fin 2) ℂ) =
      exp (t • heisenbergGenerator) := rfl

end QF10.HeisenbergFlowMonoidHom

#print axioms QF10.HeisenbergFlowMonoidHom.heisenbergGenerator_mem_skewAdjoint
#print axioms QF10.HeisenbergFlowMonoidHom.smul_heisenbergGenerator_mem_skewAdjoint
#print axioms QF10.HeisenbergFlowMonoidHom.exp_heisenbergFlow_mem_unitary
#print axioms QF10.HeisenbergFlowMonoidHom.heisenbergFlow_add
#print axioms QF10.HeisenbergFlowMonoidHom.heisenbergFlowHom
#print axioms QF10.HeisenbergFlowMonoidHom.coe_heisenbergFlowHom_apply
