/-
  QF-9 -- One-parameter group law of the Heisenberg flow `exp (t •
  heisenbergGenerator)`, `t : ℝ`. Direct extension of Wave-4 batch item
  WAVE4-QF-7 (`HeisenbergFlowUnitarity.lean`, this directory), which
  established `exp (t • heisenbergGenerator) ∈ unitary (Matrix (Fin 2)
  (Fin 2) ℂ)`. Sibling also of WAVE2-QF-5
  (`HeisenbergCommutatorFlowIdentity.lean`), WAVE3-QF-6
  (`EhrenfestExpectationValueIdentity.lean`), and WAVE5-QF-8
  (`HeisenbergFlowNormPreservation.lean`), this directory. Wave-5 batch
  item WAVE5-QF-9.

  STATUS: drafted and self-checked with `lake env lean` by the authoring
  session (single-file typecheck against the existing built Mathlib
  cache, NOT a full `lake build` -- see the Wave-5 task instructions on
  build contention with 14 concurrent sibling agents). Not registered in
  `TamesisLab.lean`; free-standing, following the precedent of every
  other file in this directory, none of which import each other -- only
  Mathlib. Consistent with that precedent, this file does NOT `import`
  `HeisenbergFlowUnitarity.lean` as a Lean module; instead it re-declares
  the identical `heisenbergGenerator` definition locally (see below),
  citing its QF-4 origin.

  HONESTY NOTE (mandatory, per `../SCOPE.md` in this directory's parent).
  "Quantum-Classical Unification" (QCU-001) is a lab-internal extension,
  informally numbered "Problem 8", added at explicit user request. It is
  **not** one of the seven Clay Millennium Problems, has no official
  recognition, no $1,000,000 prize, and no single agreed formal
  statement. This file makes ZERO claim that any Millennium problem
  (Clay-official or otherwise) is solved, approximated, or reachable,
  and ZERO claim of mathematical novelty: that a one-parameter family
  `t ↦ exp(tH)` generated by a FIXED element `H` of a Banach algebra
  satisfies the group law `exp((s+t)H) = exp(sH)·exp(tH)` is one of the
  most standard facts in operator theory (`H` trivially commutes with
  any scalar multiple of itself, so the identity is an immediate
  instance of `NormedSpace.exp_add_of_commute`), assembled here from one
  existing Mathlib lemma applied at a concrete instance, not a new
  theorem.

  MOTIVATION / WHAT THIS FILE DOES, exactly as scoped by the Wave-5
  plan. QF-7 proved `exp (t • heisenbergGenerator) ∈ unitary (Matrix
  (Fin 2) (Fin 2) ℂ)` for every `t : ℝ`, and QF-8 (sibling, this
  directory) connects that to norm/inner-product preservation, but
  neither touches the ALGEBRAIC one-parameter-group structure of the
  flow itself -- i.e. that composing the flow at two times `s` and `t`
  equals running it once at `s + t`. This file closes exactly that one
  gap: `exp ((s + t) • heisenbergGenerator) = exp (s •
  heisenbergGenerator) * exp (t • heisenbergGenerator)` for every `s t :
  ℝ`, via the prescribed method:
    (1) `add_smul` to rewrite `(s + t) • H` as `s • H + t • H`;
    (2) `NormedSpace.exp_add_of_commute`
        (`Mathlib/Analysis/Normed/Algebra/Exponential.lean:520`), which
        needs only `Commute (s • H) (t • H)` and the ambient
        `[NormedRing 𝔸] [NormedAlgebra ℚ 𝔸] [CompleteSpace 𝔸]` instances
        that `exp` itself needs (no `star`/skew-adjointness anywhere --
        this identity is a bare Banach-algebra fact about ANY fixed
        element, skew-Hermitian or not);
    (3) the commutation fact itself, `Commute (s • H) (t • H)`, built
        from `Commute.refl H : Commute H H` via two scalar-slide steps,
        `.smul_right t : Commute H (t • H)` then
        `.smul_left s : Commute (s • H) (t • H)` -- `H` trivially
        commutes with itself, and commutation is preserved under
        scalar multiplication of either side.
  RESULT: this closes with ZERO friction under `Matrix.Norms.Operator`
  (the simpler of the two scopes used elsewhere in this directory),
  tried first per the plan's own instruction. Unlike QF-7's unitarity
  result -- which needed `ContinuousStar` and hence the
  `Matrix.Norms.L2Operator` scope specifically -- the group law needs
  NO `star`-compatibility at all: `exp_add_of_commute` lives in the
  "Rat" section of `Exponential.lean`, gated only on `[NormedRing 𝔸]
  [NormedAlgebra ℚ 𝔸] [CompleteSpace 𝔸]`, none of which involve `star`.
  So the plan's own risk condition (that `Matrix.Norms.Operator` might
  fail to supply some needed instance, forcing a switch to
  `Matrix.Norms.L2Operator` as QF-7 had to) did NOT trigger here:
  `Matrix.linftyOpNormedRing` / `Matrix.linftyOpNormedAlgebra`
  (`Mathlib/Analysis/Matrix/Normed.lean:393,401`, both `scoped[
  Matrix.Norms.Operator] instance`) supply `NormedRing (Matrix (Fin 2)
  (Fin 2) ℂ)` and `NormedAlgebra ℂ (Matrix (Fin 2) (Fin 2) ℂ)` directly,
  `CompleteSpace (Matrix (Fin 2) (Fin 2) ℂ)` follows automatically
  (finite-dimensional normed space over the complete field `ℂ`), and
  `NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ)` is supplied by hand via
  `NormedAlgebra.restrictScalars ℚ ℂ (Matrix (Fin 2) (Fin 2) ℂ)` --
  exactly the same instance QF-7 supplies by hand for the same reason
  (`NormedAlgebra ℚ 𝔸` is deliberately not registered as a global
  instance, to avoid a diamond, per the precedent at
  `Mathlib/Analysis/Normed/Algebra/Spectrum.lean:374` and
  `QuaternionExponential.lean:110`). **SCOPE ANSWER (as requested by the
  plan): `Matrix.Norms.Operator` is the scope that actually closed this
  file** -- no fallback to `Matrix.Norms.L2Operator` was needed.

  MATHLIB TOOLS USED (verified present by direct read of the vendored
  snapshot at `04_FORMAL_RESEARCH_LAB/05_FORMAL/lean/.lake/packages/mathlib`,
  in addition to compiling cleanly via `lake env lean`):
    - `add_smul` (generic `DistribSMul`/module fact,
      `Mathlib/Algebra/Group/Action/Defs.lean` and
      `Mathlib/Algebra/Module/Defs.lean`) `(s + t) • x = s • x + t • x`,
      instantiated at `s t : ℝ`, `x := heisenbergGenerator : Matrix
      (Fin 2) (Fin 2) ℂ`, fed by the standard `Module ℝ (Matrix (Fin 2)
      (Fin 2) ℂ)` instance (entrywise, via `Module ℝ ℂ`).
    - `Commute.refl`, `Commute.smul_right`, `Commute.smul_left`
      (`Mathlib/Algebra/Group/Action/Defs.lean:397-403`) -- the exact
      three-step chain the falsifiable test names:
      `((Commute.refl heisenbergGenerator).smul_right t).smul_left s :
      Commute (s • heisenbergGenerator) (t • heisenbergGenerator)`, fed
      by the generic `SMulCommClass ℝ 𝔸 𝔸` / `IsScalarTower ℝ 𝔸 𝔸`
      instances that follow automatically from `Algebra ℝ (Matrix
      (Fin 2) (Fin 2) ℂ)` (itself following from `Algebra ℝ ℂ` via the
      standard `Matrix.instAlgebra` scalar-diagonal-embedding instance).
    - `NormedSpace.exp_add_of_commute`
      (`Mathlib/Analysis/Normed/Algebra/Exponential.lean:520`, `section
      Rat`, `variable {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℚ 𝔸]
      [CompleteSpace 𝔸]`) `{x y : 𝔸} (hxy : Commute x y) : exp (x + y) =
      exp x * exp y`, instantiated at `𝔸 := Matrix (Fin 2) (Fin 2) ℂ`,
      `x := s • heisenbergGenerator`, `y := t • heisenbergGenerator`, fed
      by the commutation fact above.
    - `Matrix.linftyOpNormedRing`, `Matrix.linftyOpNormedAlgebra`
      (`Mathlib/Analysis/Matrix/Normed.lean:393,401`, both `scoped[
      Matrix.Norms.Operator] instance`, activated via `open scoped
      Matrix.Norms.Operator`) supply `NormedRing (Matrix (Fin 2)
      (Fin 2) ℂ)` and `NormedAlgebra ℂ (Matrix (Fin 2) (Fin 2) ℂ)`.
    - `NormedAlgebra.restrictScalars` (`Mathlib/Analysis/Normed/Algebra/
      Basic.lean`, same precedent as QF-7 cites: `Spectrum.lean:374`,
      `QuaternionExponential.lean:110`), supplied by hand for `R := ℚ`,
      `𝕜 := ℂ`, `A := Matrix (Fin 2) (Fin 2) ℂ`, discharging the
      `[NormedAlgebra ℚ 𝔸]` hypothesis of `exp_add_of_commute`.

  WHAT THIS FILE DOES / THE FALSIFIABLE TEST, exactly as specified. Fix
  the same `2 × 2` skew-Hermitian generator `heisenbergGenerator =
  diag(i, -i)` as QF-4/QF-5/QF-6/QF-7/QF-8. Prove
  `exp ((s + t) • heisenbergGenerator) = exp (s • heisenbergGenerator) *
  exp (t • heisenbergGenerator)` for every `s t : ℝ`, via exactly the
  prescribed method: `NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ)`
  supplied by `NormedAlgebra.restrictScalars`, `add_smul`, then
  `exp_add_of_commute` fed by the `Commute.refl`/`smul_right`/
  `smul_left` chain. Tried first, and closing, under the simpler
  `Matrix.Norms.Operator` scope (see "SCOPE ANSWER" above), per the
  plan's own instruction to attempt that scope first.

  WHAT IS STILL MISSING even on full success of this file (stated
  honestly, per the Wave-5 instructions, mirroring QF-4/QF-5/QF-6/QF-7/
  QF-8's own honesty sections). This file proves ONLY the bare
  one-parameter-group addition law `exp((s+t)H) = exp(sH)·exp(tH)` for
  the fixed toy generator `heisenbergGenerator` at real time parameters
  `s, t`. It does **not**: (a) prove that `t ↦ exp(t • heisenbergGenerator)`
  is a homomorphism from `(ℝ, +)` into any bundled group structure (e.g.
  `unitary (Matrix (Fin 2) (Fin 2) ℂ)` as a `Submonoid`/group, or a
  `Monoid.End`/`OneParameterGroup`-style bundled object) -- only the raw
  pointwise equation is proved, no bundling into a `MonoidHom` or similar
  is attempted; (b) additionally establish `exp (0 • heisenbergGenerator)
  = 1` or the inverse law `exp ((-t) • heisenbergGenerator) = (exp (t •
  heisenbergGenerator))⁻¹`, which together with this file's identity
  would complete a full group-law package -- both are standard
  one-line corollaries of existing Mathlib lemmas (`exp_zero`,
  `NormedSpace.exp_neg` or unitary-submonoid inverse facts) but are
  NOT proved here, out of this file's exact narrow scope; (c) connect
  to QF-7's unitarity or QF-8's norm-preservation results -- this file
  is purely about the additive structure of the flow in the algebra
  `Matrix (Fin 2) (Fin 2) ℂ`, with no reference to `unitary`, `star`, or
  any inner product; (d) prove any Ehrenfest theorem, correspondence-
  principle statement, or physical Heisenberg/Schrödinger equation of
  motion -- those are the separate concerns of QF-5/QF-6 in this same
  directory; (e) generalize beyond a fixed finite dimension / bounded
  operator (per QF-2/QF-3 in this same directory, this bounded/
  finite-dimensional setting cannot even realize the canonical
  commutation relation, so `heisenbergGenerator` is explicitly NOT a
  physical Hamiltonian); (f) connect to any `ħ → 0` classical limit or
  any physical interpretation of the group law beyond the bare algebraic
  identity.
-/
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Matrix.Normed

open scoped Matrix.Norms.Operator
open NormedSpace

namespace QF9.HeisenbergFlowGroupLaw

/-- The fixed generator for this probe, identical to QF-4's/QF-5's/QF-6's/
QF-7's/QF-8's `heisenbergGenerator`: `H = diag(i, -i)`, a concrete
`2 × 2` skew-Hermitian complex matrix. Re-declared locally rather than
imported, per this directory's established free-standing-file precedent
(see the header note above). Playing the role of a toy "Hamiltonian-like"
generator for the purposes of this single-identity feasibility test; NOT
claimed to be a physical Hamiltonian (real position/momentum generators
are unbounded, per QF-2 / QF-3 in this same directory). Note: this
file's main result does not actually use skew-Hermitian-ness at all
(see the file header) -- the generator is fixed here purely to match the
concrete instance every sibling file in this directory uses. -/
noncomputable def heisenbergGenerator : Matrix (Fin 2) (Fin 2) ℂ :=
  !![Complex.I, 0; 0, -Complex.I]

/-- **Main result (QF-9), the falsifiable test exactly as specified.**
The Heisenberg flow `t ↦ exp (t • heisenbergGenerator)` satisfies the
one-parameter-group addition law: `exp ((s + t) • heisenbergGenerator) =
exp (s • heisenbergGenerator) * exp (t • heisenbergGenerator)` for every
`s t : ℝ`. Closed under the `Matrix.Norms.Operator` scope (the simpler
of the two scopes used in this directory), per the plan's instruction to
try that scope first -- no fallback to `Matrix.Norms.L2Operator` was
needed, since `exp_add_of_commute` requires no `star`-compatibility
instance (unlike QF-7's unitarity result). -/
theorem heisenbergFlow_add (s t : ℝ) :
    exp ((s + t) • heisenbergGenerator) =
      exp (s • heisenbergGenerator) * exp (t • heisenbergGenerator) := by
  haveI : NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ) :=
    NormedAlgebra.restrictScalars ℚ ℂ (Matrix (Fin 2) (Fin 2) ℂ)
  rw [add_smul]
  exact exp_add_of_commute
    (((Commute.refl heisenbergGenerator).smul_right t).smul_left s)

end QF9.HeisenbergFlowGroupLaw

#print axioms QF9.HeisenbergFlowGroupLaw.heisenbergFlow_add
