/-
  QF-12 -- Packaging the Heisenberg flow `t ↦ exp (t • heisenbergGenerator)`
  as a full `ContinuousMonoidHom (Multiplicative ℝ) (unitary (Matrix (Fin 2)
  (Fin 2) ℂ))`, i.e. upgrading Wave-6 batch item WAVE6-QF-10's bare
  algebraic `heisenbergFlowHom : Multiplicative ℝ →* unitary (...)`
  (`HeisenbergFlowMonoidHom.lean`, this directory) with the continuity fact
  established in isolation by Wave-6 batch item WAVE6-QF-11
  (`continuous_exp_smul_heisenbergGenerator`, `HeisenbergFlowContinuitySmulProbe.lean`,
  this directory), exactly the gap QF-11's own "WHAT IS STILL MISSING"
  section named as the next step it was de-risking. Wave-7 batch item
  WAVE7-QF-12.

  STATUS: drafted and self-checked with `lake env lean` by the authoring
  session (single-file typecheck against the existing built Mathlib
  cache, NOT a full `lake build` -- 13 concurrent sibling agents this
  wave). Not registered in `TamesisLab.lean`; free-standing, following
  this directory's established precedent that no file here imports
  another as a Lean module. Consistent with that precedent, this file
  re-declares `heisenbergGenerator` and re-derives the QF-7 unitarity
  fact, the QF-9 addition law, and the QF-11 continuity fact locally,
  citing their QF-7/QF-9/QF-11 origin, rather than importing
  `HeisenbergFlowMonoidHom.lean` / `HeisenbergFlowContinuitySmulProbe.lean`.

  HONESTY NOTE (mandatory, per `../SCOPE.md` in this directory's parent).
  "Quantum-Classical Unification" (QCU-001) is a lab-internal extension,
  informally numbered "Problem 8", added at explicit user request. It is
  **not** one of the seven Clay Millennium Problems, has no official
  recognition, no $1,000,000 prize, and no single agreed formal
  statement. This file makes ZERO claim that any Millennium problem
  (Clay-official or otherwise) is solved, approximated, or reachable,
  and ZERO claim of mathematical novelty: that a one-parameter flow
  `t ↦ exp(tH)` generated by a fixed bounded skew-adjoint operator `H`
  is a continuous homomorphism out of the additive reals -- the textbook
  definition of a (uniformly continuous, bounded-generator) one-parameter
  unitary group -- is completely standard operator theory. This file adds
  no new mathematical content beyond re-packaging QF-10's `MonoidHom` and
  QF-11's continuity fact into one bundled `ContinuousMonoidHom` term.

  MOTIVATION / WHAT THIS FILE DOES, exactly as scoped by the Wave-7 plan.
  QF-10 built the bare algebraic bundle `heisenbergFlowHom : Multiplicative
  ℝ →* unitary (Matrix (Fin 2) (Fin 2) ℂ)`. QF-11 proved, in isolation,
  `continuous_exp_smul_heisenbergGenerator : Continuous (fun t : ℝ => exp
  (t • heisenbergGenerator))` and explicitly flagged that assembling this
  into a `ContinuousMonoidHom` packaging of `heisenbergFlowHom` was the
  next, NOT-yet-attempted step. This file closes exactly that gap, via the
  falsifiable test's own prescribed method: `{ heisenbergFlowHom with
  continuous_toFun := ... }`, discharging `continuous_toFun` by composing
  QF-11's continuity fact with `continuous_toAdd`
  (`Mathlib/Topology/Constructions.lean:111`, `Continuous (toAdd :
  Multiplicative X → X) := continuous_id`, since the topology on
  `Multiplicative X` is defined to be literally `‹TopologicalSpace X›`)
  and pairing the result with `Continuous.subtype_mk`
  (`Mathlib/Topology/Constructions.lean:413`) to land inside the `unitary`
  subtype.

  RESULT: closes with ZERO friction beyond re-deriving QF-7/QF-9/QF-11's
  own pointwise facts (all reused, not re-invented). **SCOPE ANSWER (as
  requested by the plan): `Matrix.Norms.L2Operator` is the scope that
  actually closes this file**, for the identical reason QF-10 and QF-11
  each already documented -- it is the only scope supplying both
  `ContinuousStar` (needed transitively for QF-7's unitarity membership
  fact, reused here) and, via `NormedSpace.complexToReal`
  (`Mathlib/Analysis/Complex/Basic.lean:80`), the `ContinuousSMul ℝ
  (Matrix (Fin 2) (Fin 2) ℂ)` instance QF-11 found friction-free under
  this same scope. No new instance-synthesis risk was hit beyond what
  QF-10/QF-11 already surveyed: `TopologicalSpace (Multiplicative ℝ)` is
  an unconditional global instance
  (`Mathlib/Topology/Constructions.lean:86`, literally `‹TopologicalSpace
  ℝ›`), and `TopologicalSpace (unitary (Matrix (Fin 2) (Fin 2) ℂ))` is the
  automatic subtype instance inherited from the ambient
  `Matrix.instL2OpNormedRing`'s metric topology -- neither needed a
  hand-supplied `haveI`.

  MATHLIB TOOLS USED beyond those already cited by QF-7/QF-9/QF-10/QF-11
  (see those files' headers for the full citation trail on
  `skewAdjoint.smul_mem`, `exp_mem_unitary_of_mem_skewAdjoint`,
  `NormedAlgebra.restrictScalars`, `NormedSpace.exp_add_of_commute`,
  `MonoidHom.mk'`, `NormedSpace.complexToReal`, `Continuous.smul`):
    - `ContinuousMonoidHom` (`Mathlib/Topology/Algebra/ContinuousMonoidHom.lean:57`,
      `structure ContinuousMonoidHom extends A →* B, C(A, B)`, flattening
      to fields `toFun`, `map_one'`, `map_mul'`, `continuous_toFun`) --
      the target bundled type the falsifiable test names.
    - `continuous_toAdd` (`Mathlib/Topology/Constructions.lean:111`,
      `Continuous (toAdd : Multiplicative X → X) := continuous_id`,
      `import Mathlib.Topology.Constructions` required explicitly since
      `ContinuousMonoidHom`'s own default imports do not pull it in).
    - `Continuous.subtype_mk` (`Mathlib/Topology/Constructions.lean:413`,
      `Continuous f → (∀ x, p (f x)) → Continuous (fun x => (⟨f x, hp
      x⟩ : Subtype p))`), used to land the composite continuity fact
      inside the `unitary` subtype.

  WHAT THIS FILE DOES / THE FALSIFIABLE TEST, exactly as specified. Fix
  the same `2 × 2` skew-Hermitian generator `heisenbergGenerator =
  diag(i, -i)` as QF-4/.../QF-11. Construct
  `heisenbergFlowContinuousHom : ContinuousMonoidHom (Multiplicative ℝ)
  (unitary (Matrix (Fin 2) (Fin 2) ℂ))` via `{ heisenbergFlowHom with
  continuous_toFun := ... }` exactly as the falsifiable test's primary
  route prescribes, discharging `continuous_toFun` by
  `continuous_exp_smul_heisenbergGenerator.comp continuous_toAdd`, fed
  into `Continuous.subtype_mk`. **SCOPE ANSWER: `Matrix.Norms.L2Operator`
  is the scope that actually closed this file** (see "RESULT" above).

  WHAT IS STILL MISSING even on full success of this file (stated
  honestly, mirroring QF-4/.../QF-11's own honesty sections). This file
  proves ONLY that `heisenbergFlowHom` upgrades to a bundled
  `ContinuousMonoidHom`. It does **not**: (a) prove any Ehrenfest
  theorem, Schrödinger/Heisenberg equation of motion, or
  correspondence-principle statement -- QF-5/QF-6's separate concerns;
  (b) extend to `t : ℂ` or to any unbounded/physical position-momentum
  generator (per QF-2/QF-3, this bounded/finite-dimensional setting
  cannot realize the canonical commutation relation, so
  `heisenbergGenerator` is explicitly NOT a physical Hamiltonian); (c)
  connect to QF-8's norm/inner-product preservation results; (d) prove
  injectivity/surjectivity or any structural property of the flow beyond
  it being a continuous group homomorphism; (e) prove `Continuous`
  jointly in `(t, generator)` or any generator-independence /
  differentiability statement (QF-11's own sibling, `HeisenbergFlowDerivativeProbe.lean`,
  is the separate probe for differentiability, not extended here); (f)
  connect to any `ħ → 0` classical limit or physical interpretation
  beyond the bare topological-algebraic packaging.
-/
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.Algebra.Star.Module
import Mathlib.Analysis.RCLike.Basic
import Mathlib.Algebra.Star.Unitary
import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Topology.Algebra.ContinuousMonoidHom
import Mathlib.Topology.Constructions

open scoped Matrix.Norms.L2Operator
open NormedSpace

namespace QF12.HeisenbergFlowContinuousMonoidHom

/-- The fixed generator for this probe, identical to QF-4's/.../QF-11's
`heisenbergGenerator`: `H = diag(i, -i)`. Re-declared locally rather than
imported, per this directory's free-standing-file precedent. -/
noncomputable def heisenbergGenerator : Matrix (Fin 2) (Fin 2) ℂ :=
  !![Complex.I, 0; 0, -Complex.I]

/-- Skew-adjoint membership, identical to QF-7/QF-9/QF-10/QF-11's
`heisenbergGenerator_mem_skewAdjoint`, re-derived locally. -/
theorem heisenbergGenerator_mem_skewAdjoint :
    heisenbergGenerator ∈ skewAdjoint (Matrix (Fin 2) (Fin 2) ℂ) := by
  rw [skewAdjoint.mem_iff, Matrix.star_eq_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [heisenbergGenerator, Matrix.conjTranspose_apply]

/-- Scalar skew-adjointness, identical to QF-7/.../QF-11's
`smul_heisenbergGenerator_mem_skewAdjoint`, re-derived locally. -/
theorem smul_heisenbergGenerator_mem_skewAdjoint (t : ℝ) :
    t • heisenbergGenerator ∈ skewAdjoint (Matrix (Fin 2) (Fin 2) ℂ) :=
  skewAdjoint.smul_mem t heisenbergGenerator_mem_skewAdjoint

/-- QF-7's unitarity result, re-derived locally under `Matrix.Norms.L2Operator`. -/
theorem exp_heisenbergFlow_mem_unitary (t : ℝ) :
    exp (t • heisenbergGenerator) ∈ unitary (Matrix (Fin 2) (Fin 2) ℂ) :=
  haveI : NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ) :=
    NormedAlgebra.restrictScalars ℚ ℂ (Matrix (Fin 2) (Fin 2) ℂ)
  exp_mem_unitary_of_mem_skewAdjoint (smul_heisenbergGenerator_mem_skewAdjoint t)

/-- QF-9's addition law, re-derived locally under `Matrix.Norms.L2Operator`
(as QF-10 already re-derives it, for the same reason: QF-7's unitarity
above forces this scope). -/
theorem heisenbergFlow_add (s t : ℝ) :
    exp ((s + t) • heisenbergGenerator) =
      exp (s • heisenbergGenerator) * exp (t • heisenbergGenerator) := by
  haveI : NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ) :=
    NormedAlgebra.restrictScalars ℚ ℂ (Matrix (Fin 2) (Fin 2) ℂ)
  rw [add_smul]
  exact exp_add_of_commute
    (((Commute.refl heisenbergGenerator).smul_right t).smul_left s)

/-- QF-11's continuity fact for the full flow, re-derived locally under
`Matrix.Norms.L2Operator`, identical statement and proof to QF-11's
`continuous_exp_smul_heisenbergGenerator`. -/
theorem continuous_exp_smul_heisenbergGenerator :
    Continuous (fun t : ℝ => exp (t • heisenbergGenerator)) :=
  haveI : NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℂ) :=
    NormedAlgebra.restrictScalars ℚ ℂ (Matrix (Fin 2) (Fin 2) ℂ)
  NormedSpace.exp_continuous.comp (continuous_id.smul continuous_const)

/-- QF-10's bundled `MonoidHom`, re-derived locally, identical statement
and proof to QF-10's `heisenbergFlowHom`. -/
noncomputable def heisenbergFlowHom :
    Multiplicative ℝ →* unitary (Matrix (Fin 2) (Fin 2) ℂ) :=
  MonoidHom.mk'
    (fun t => ⟨exp (t.toAdd • heisenbergGenerator),
      exp_heisenbergFlow_mem_unitary t.toAdd⟩)
    (fun a b => by
      apply Subtype.ext
      show exp ((a * b).toAdd • heisenbergGenerator) =
          exp (a.toAdd • heisenbergGenerator) * exp (b.toAdd • heisenbergGenerator)
      rw [toAdd_mul]
      exact heisenbergFlow_add a.toAdd b.toAdd)

/-- **Main result (QF-12), the falsifiable test exactly as specified.**
`heisenbergFlowHom` upgrades to a full `ContinuousMonoidHom (Multiplicative
ℝ) (unitary (Matrix (Fin 2) (Fin 2) ℂ))`, via `{ heisenbergFlowHom with
continuous_toFun := ... }` exactly as prescribed, discharging
`continuous_toFun` by composing QF-11's `continuous_exp_smul_heisenbergGenerator`
with `continuous_toAdd` and landing in the `unitary` subtype via
`Continuous.subtype_mk`. Closes under `Matrix.Norms.L2Operator` (see the
file header's "SCOPE ANSWER"). -/
noncomputable def heisenbergFlowContinuousHom :
    ContinuousMonoidHom (Multiplicative ℝ) (unitary (Matrix (Fin 2) (Fin 2) ℂ)) :=
  { heisenbergFlowHom with
    continuous_toFun :=
      Continuous.subtype_mk
        (continuous_exp_smul_heisenbergGenerator.comp continuous_toAdd)
        (fun t => exp_heisenbergFlow_mem_unitary t.toAdd) }

/-- Sanity-check corollary, immediate from `heisenbergFlowContinuousHom`'s
bundled structure: the underlying matrix at `Multiplicative.ofAdd t` is
exactly the flow value `exp (t • heisenbergGenerator)`, confirming the
packaging did not silently change the underlying object. Not part of the
falsifiable test itself. -/
theorem coe_heisenbergFlowContinuousHom_apply (t : ℝ) :
    (heisenbergFlowContinuousHom (Multiplicative.ofAdd t) : Matrix (Fin 2) (Fin 2) ℂ) =
      exp (t • heisenbergGenerator) := rfl

end QF12.HeisenbergFlowContinuousMonoidHom

#print axioms QF12.HeisenbergFlowContinuousMonoidHom.heisenbergGenerator_mem_skewAdjoint
#print axioms QF12.HeisenbergFlowContinuousMonoidHom.smul_heisenbergGenerator_mem_skewAdjoint
#print axioms QF12.HeisenbergFlowContinuousMonoidHom.exp_heisenbergFlow_mem_unitary
#print axioms QF12.HeisenbergFlowContinuousMonoidHom.heisenbergFlow_add
#print axioms QF12.HeisenbergFlowContinuousMonoidHom.continuous_exp_smul_heisenbergGenerator
#print axioms QF12.HeisenbergFlowContinuousMonoidHom.heisenbergFlowHom
#print axioms QF12.HeisenbergFlowContinuousMonoidHom.heisenbergFlowContinuousHom
#print axioms QF12.HeisenbergFlowContinuousMonoidHom.coe_heisenbergFlowContinuousHom_apply
