/-
  QF-4 -- single-lemma feasibility probe for the derivative of the
  Heisenberg-picture flow t ↦ exp(t • H) generated by a skew-Hermitian
  matrix H. Wave-1 batch item.

  STATUS: drafted and self-checked with `lake env lean` by the authoring
  session (single-file typecheck against the existing built Mathlib
  cache, NOT a full `lake build` -- see the Wave-1 task instructions on
  build contention with 26 concurrent sibling agents). Not registered in
  `TamesisLab.lean`; free-standing, following the precedent of
  `../CCRFiniteDimImpossibility.lean` (QF-2) and
  `../GelfandSelfAdjointRealValued.lean` (QF-3) in this same directory.

  HONESTY NOTE (mandatory, per `../SCOPE.md` in this directory's parent).
  "Quantum-Classical Unification" (QCU-001) is a lab-internal extension,
  informally numbered "Problem 8", added at explicit user request. It is
  **not** one of the seven Clay Millennium Problems, has no official
  recognition, no $1,000,000 prize, and no single agreed formal
  statement. This file makes ZERO claim that any Millennium problem
  (Clay-official or otherwise) is solved, approximated, or reachable,
  and ZERO claim of mathematical novelty: the derivative-of-matrix-
  exponential fact used here is a two-line instantiation of an existing
  Mathlib lemma (`hasFDerivAt_exp_smul_const_of_mem_ball`), not a new
  theorem.

  MOTIVATION / WHY THIS NARROW TEST, NOT THE FULL EHRENFEST STATEMENT.
  The recon proposal for QF-4 was to check whether a bounded-operator
  Ehrenfest identity `d/dt ⟨ψ, A(t) ψ⟩ = ⟨ψ, i[H, A(t)] ψ⟩` (Heisenberg
  picture, `A(t) = exp(-tH)·A·exp(tH)`) is reachable cheaply from
  existing `NormedSpace`/`Matrix.exp` derivative API. An adversarial
  review (recorded upstream, not reproduced in full here) found this
  test UNDER-SCOPED: `Analysis/Normed/Algebra/MatrixExponential.lean`
  has ZERO `HasFDerivAt`/`HasDerivAt` lemmas specific to `Matrix.exp`,
  and the general `hasFDerivAt_exp` in
  `Analysis/SpecialFunctions/Exponential.lean` needs `NormedCommRing`,
  which does NOT apply to the noncommuting matrix algebra. The correct
  tool is instead `hasFDerivAt_exp_smul_const_of_mem_ball` (derivative
  of `u ↦ exp(u • x)` for `u` ranging over a *commutative* scalar type
  `𝕊` acting on a fixed element `x` of a possibly-noncommutative complete
  normed algebra `𝔸`), together with a nontrivial 3-factor product-rule
  assembly (conjugation `exp(-tH)·A·exp(tH)`, commutation of `exp(tH)`
  with `H`, and differentiation of the sesquilinear inner-product
  expectation) to reach the full Ehrenfest identity -- assembly work
  that is NOT attempted in this file. The revised, narrowed test
  (this file) checks ONLY the single foundational step: does
  `hasFDerivAt_exp_smul_const_of_mem_ball` actually instantiate for a
  concrete skew-Hermitian matrix in the matrix algebra, with the
  `Metric.eball`/radius-of-convergence side condition discharging
  cleanly (finite-dimensional matrix algebras should have infinite
  radius of convergence for the exponential series, per
  `expSeries_radius_eq_top`) rather than assumed. If this closes
  cleanly, the full 3-factor Ehrenfest assembly is a separate,
  larger-scoped follow-on task, NOT attempted here.

  MATHLIB TOOLS USED (verified present by direct read of the vendored
  snapshot at `04_FORMAL_RESEARCH_LAB/05_FORMAL/lean/.lake/packages/mathlib`,
  in addition to compiling cleanly via `lake env lean`):
    - `hasFDerivAt_exp_smul_const_of_mem_ball`
      (`Mathlib/Analysis/SpecialFunctions/Exponential.lean:256`)
      `HasFDerivAt (fun u : 𝕊 => exp (u • x)) (exp (t • x) •
        (1 : 𝕊 →L[𝕂] 𝕊).smulRight x) t`, given `t • x ∈ Metric.eball 0
        (expSeries 𝕂 𝔸).radius`, for `𝕂` a `NontriviallyNormedField` +
      `CharZero`, `𝕊` a `NormedCommRing` + `NormedSpace 𝕂 𝕊`, `𝔸` a
      complete `NormedRing` + `NormedAlgebra 𝕂 𝔸` with `Algebra 𝕊 𝔸`,
      `ContinuousSMul 𝕊 𝔸`, `IsScalarTower 𝕂 𝕊 𝔸`.
    - `expSeries_radius_eq_top`
      (`Mathlib/Analysis/Normed/Algebra/Exponential.lean:451`)
      `(expSeries 𝕂 𝔸).radius = ⊤` unconditionally for any complete
      normed algebra `𝔸` over an `RCLike`-style field `𝕂` (no finite-
      dimensionality hypothesis needed at all -- it holds for every
      Banach algebra, matrix or not).
    - `edist_lt_top` (`Mathlib/Topology/MetricSpace/Pseudo/Defs.lean:315`)
      generic fact `edist x y < ⊤` in any `PseudoMetricSpace`, used to
      discharge membership in `Metric.eball 0 ⊤ = Set.univ` up to this
      unfolding.
    - `NormedField.toNormedCommRing`
      (`Mathlib/Analysis/Normed/Field/Basic.lean:194`) supplies
      `NormedCommRing ℂ` automatically from `NormedField ℂ`, needed to
      instantiate `𝕊 := ℂ`.
    - `Matrix.Norms.Operator` scoped instances
      (`Mathlib/Analysis/Matrix/Normed.lean:469-481`,
      specifically `Matrix.linftyOpNormedRing` and
      `Matrix.linftyOpNormedAlgebra`), opened via
      `open scoped Matrix.Norms.Operator`, to activate ONE concrete
      choice of norm on `Matrix (Fin n) (Fin n) ℂ` (the file's own
      docstring confirms no norm on `Matrix` is registered as a global
      instance by default, precisely because several incompatible
      choices exist -- L∞-operator, Frobenius, L²-operator/C⋆).
      `CompleteSpace (Matrix (Fin n) (Fin n) ℂ)` and `Algebra ℂ
      (Matrix (Fin n) (Fin n) ℂ)` are then found automatically
      (finite-dimensional normed space over the complete field `ℂ`,
      resp. the standard scalar-matrix algebra structure).

  WHAT THIS FILE DOES / THE FALSIFIABLE TEST, exactly as narrowed by the
  adversarial reviewer. Fix a concrete `2 × 2` skew-Hermitian complex
  matrix `H := diag(i, -i)` (checked directly: `Hᴴ = -H`). Instantiate
  `hasFDerivAt_exp_smul_const_of_mem_ball` at `𝕂 = 𝕊 = ℂ`, `x = H`, for
  an arbitrary base point `t₀ : ℂ`, discharging the ball-membership
  side condition via `expSeries_radius_eq_top` + `edist_lt_top` (two
  `exact`-level facts, no new infrastructure). RESULT: this instantiates
  and typechecks with ZERO friction beyond activating one norm instance
  on `Matrix (Fin 2) (Fin 2) ℂ` via `open scoped
  Matrix.Norms.Operator` -- the test's own falsification condition
  ("if it requires building differentiability-of-operator-valued-curve
  infrastructure from scratch, deprioritize") is NOT triggered: no new
  infrastructure was built, only an existing general lemma was applied
  at a concrete instance.

  WHAT IS STILL MISSING even on full success of this file (stated
  honestly, per Wave-1 instructions). This file proves ONLY that the
  single derivative-of-`u ↦ exp(u • H)` step is cheap. It does **not**:
  (a) prove any Ehrenfest identity, Heisenberg-picture evolution law,
  or correspondence-principle statement; (b) handle the commutator
  `[H, A]`, the 3-factor conjugation `exp(-tH)·A·exp(tH)`, or the
  product rule needed to differentiate it; (c) touch the inner-product
  expectation `⟨ψ, A(t) ψ⟩` or its derivative at all; (d) generalize
  beyond a fixed finite dimension / bounded operator (per QF-2 in this
  same directory, this bounded/finite-dimensional setting cannot even
  realize the canonical commutation relation, so this file's `H` is
  explicitly NOT a physical position/momentum-type generator); (e)
  connect to any `ħ → 0` classical limit. Per the reviewer's own
  narrowing instructions, the full 3-factor Ehrenfest assembly remains
  a separate, larger-scoped, NOT-attempted follow-on task. This file is
  a scoping result about feasibility of one sub-step, not a step toward
  any SCOPE.md facet by itself.
-/
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Matrix.Normed

open scoped Matrix.Norms.Operator
open NormedSpace

namespace QF4.HeisenbergFlowDerivativeProbe

/-- The fixed generator for this probe: `H = diag(i, -i)`, a concrete
`2 × 2` skew-Hermitian complex matrix (`Hᴴ = -H`, verified by
`heisenbergGenerator_skewHermitian` below). Playing the role of a toy
"Hamiltonian-like" generator for the purposes of this single-lemma
feasibility test; NOT claimed to be a physical Hamiltonian (see the
HONESTY NOTE above: real position/momentum generators are unbounded,
per QF-2/QF-3 in this same directory). -/
noncomputable def heisenbergGenerator : Matrix (Fin 2) (Fin 2) ℂ :=
  !![Complex.I, 0; 0, -Complex.I]

/-- **Skew-Hermitian check.** `heisenbergGenerator` satisfies
`Hᴴ = -H`, the defining property of a skew-adjoint (skew-Hermitian)
matrix -- the generator of a one-parameter group of unitaries in the
physical picture (`exp(tH)` is unitary for skew-Hermitian `H`), though
unitarity itself is not needed for, and is not proved by, this file. -/
theorem heisenbergGenerator_skewHermitian :
    heisenbergGenerator.conjTranspose = -heisenbergGenerator := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [heisenbergGenerator, Matrix.conjTranspose_apply]

/-- **Main result (QF-4), the narrowed falsifiable test.** The curve
`u ↦ exp(u • H)` (the Heisenberg-picture flow generated by the fixed
skew-Hermitian matrix `heisenbergGenerator`) has a Fréchet derivative
at every base point `t₀ : ℂ`, given directly by Mathlib's
`hasFDerivAt_exp_smul_const_of_mem_ball`, with the exponential-series
ball-membership side condition discharged by `expSeries_radius_eq_top`
(finite radius restrictions never bind for a complete normed algebra)
and the generic metric fact `edist_lt_top`. This is exactly the single
lemma instantiation the adversarial review asked to be checked in
isolation, BEFORE any commitment to the larger 3-factor Ehrenfest
assembly (see the file header). -/
theorem hasFDerivAt_heisenbergFlow (t₀ : ℂ) :
    HasFDerivAt (fun u : ℂ => exp (u • heisenbergGenerator))
      (exp (t₀ • heisenbergGenerator) •
        (1 : ℂ →L[ℂ] ℂ).smulRight heisenbergGenerator) t₀ := by
  apply hasFDerivAt_exp_smul_const_of_mem_ball ℂ heisenbergGenerator t₀
  exact (expSeries_radius_eq_top ℂ (Matrix (Fin 2) (Fin 2) ℂ)).symm ▸
    edist_lt_top _ _

end QF4.HeisenbergFlowDerivativeProbe

#print axioms QF4.HeisenbergFlowDerivativeProbe.heisenbergGenerator_skewHermitian
#print axioms QF4.HeisenbergFlowDerivativeProbe.hasFDerivAt_heisenbergFlow
