"""
Independent, from-scratch verification of Section 5.3's structural claims:
  - the identity E[(M_K')^t] = K! * sum_{r=0}^K C(K,r) * W(r,t)/(K+t+r+1)!
  - the closed forms W(r,1) = 2*r!*(r+1)^2, W(r,2) = r!*(r+1)*(r+2)*(2r+3)

W(r,t) is defined here (from the mathematical description in ATTEMPT.md
Section 5.3, NOT from reading find_W_pattern.py) as the size-r,
subset-independent quantity such that, for ANY single subset A of size r,
  contribution of A to E[(M_K')^t] = K! * W(r,t) / (K+t+r+1)!
i.e. W(r,t) := sum over the monomials generated by Proposition S's
expansion for A (m=r) times the multinomial expansion of the conditional
t-th moment, of  coeff * prod_i (exponent_i!)   [this is exactly what
remains after factoring the common K!/(K+r+t+1)! out of the Dirichlet
moment formula K! prod(k_i!)/(K+sum k_i)!, using that sum k_i = r+t+1
identically for every monomial arising from a size-r subset].

This is a fully independent re-derivation of the definition, using only
the prose description, and is then checked two ways:
  (1) internal consistency: does K! * sum_r C(K,r) W(r,t)/(K+t+r+1)! equal
      the route_B_moment(K,t) computed independently in adv2_moments.py
      (recomputed here from scratch, not imported)?
  (2) does the resulting W(r,1), W(r,2) match the claimed closed forms,
      for r = 0,...,8?
"""
from fractions import Fraction
from itertools import combinations
from collections import defaultdict
import math


def W(r, t):
    """
    W(r,t) computed for a single representative subset A = {0,...,r-1}
    (any subset of size r gives the same value, by symmetry of the
    Dirichlet(1,...,1)/Proposition-S construction in the source labels --
    this symmetry itself is checked separately below).
    """
    A = tuple(range(r))
    base_exp = {a: 1 for a in A}
    coeff0 = math.factorial(r)
    prop_s_terms = []
    e = dict(base_exp)
    e['D'] = e.get('D', 0) + 1
    prop_s_terms.append((Fraction(coeff0), e))
    for b in A:
        e2 = dict(base_exp)
        e2[b] = e2.get(b, 0) + 1
        prop_s_terms.append((Fraction(coeff0), e2))

    varlist = ['D'] + list(A)
    nv = len(varlist)

    def compositions(total_, parts):
        if parts == 1:
            yield (total_,)
            return
        for i in range(total_ + 1):
            for rest in compositions(total_ - i, parts - 1):
                yield (i,) + rest

    moment_terms = []
    for comp in compositions(t, nv):
        k_D = comp[0]
        ks = comp[1:]
        multinom_coeff = math.factorial(t)
        multinom_coeff //= math.factorial(k_D)
        for k in ks:
            multinom_coeff //= math.factorial(k)
        c = Fraction(multinom_coeff)
        for k in ks:
            c /= (k + 1)
        e = {}
        if k_D:
            e['D'] = k_D
        for a, k in zip(A, ks):
            if k:
                e[a] = k
        moment_terms.append((c, e))

    total = Fraction(0)
    for c1, e1 in prop_s_terms:
        for c2, e2 in moment_terms:
            combined = defaultdict(int)
            for v, p in e1.items():
                combined[v] += p
            for v, p in e2.items():
                combined[v] += p
            prod_fact = 1
            for k in combined.values():
                prod_fact *= math.factorial(k)
            total += c1 * c2 * prod_fact
    return total


def route_B_moment_fresh(K, t):
    """Recomputed independently (not imported from adv2) for the cross-check."""
    total = Fraction(0)
    for r in range(0, K + 1):
        num_subsets = math.comb(K, r)
        total += Fraction(num_subsets) * math.factorial(K) * W(r, t) / math.factorial(K + t + r + 1)
    return total


def sympy_target_moment(K, t):
    import sympy as sp
    x = sp.symbols('x', positive=True)
    dens = 2 * K * x * (1 - x**2) ** (K - 1)
    val = sp.integrate(x**t * dens, (x, 0, 1))
    val = sp.nsimplify(val)
    fr = sp.fraction(sp.together(val))
    return Fraction(int(fr[0]), int(fr[1]))


if __name__ == "__main__":
    print("=== Part 1: closed-form check for W(r,1), W(r,2), r=0..8 ===")
    all_ok1 = True
    for r in range(0, 9):
        w1 = W(r, 1)
        w1_formula = 2 * math.factorial(r) * (r + 1) ** 2
        w2 = W(r, 2)
        w2_formula = math.factorial(r) * (r + 1) * (r + 2) * (2 * r + 3)
        ok1 = (w1 == w1_formula)
        ok2 = (w2 == w2_formula)
        all_ok1 = all_ok1 and ok1 and ok2
        print(f"r={r:>2}  W(r,1)={str(w1):>12} formula={w1_formula:>12} match={ok1}   "
              f"W(r,2)={str(w2):>14} formula={w2_formula:>14} match={ok2}")
    print("ALL W(r,1)/W(r,2) CLOSED FORMS MATCH:", all_ok1)
    print()

    print("=== Part 2: identity E[(M_K')^t] = K! sum_r C(K,r) W(r,t)/(K+t+r+1)! ===")
    print("    checked against independent sympy target-density integration, K=1..6, t=1..3")
    all_ok2 = True
    for K in range(1, 7):
        for t in range(1, 4):
            lhs = route_B_moment_fresh(K, t)
            rhs = sympy_target_moment(K, t)
            ok = (lhs == rhs)
            all_ok2 = all_ok2 and ok
            print(f"K={K} t={t}  W-based={str(lhs):>16}  target={str(rhs):>16}  match={ok}")
    print("ALL IDENTITY CHECKS MATCH:", all_ok2)
    print()

    print("=== Part 3: symmetry check -- W(r,t) same for ANY subset of size r, not just {0,...,r-1} ===")
    # Recompute W for a subset that is NOT a prefix, e.g. for K=5, r=2, use subset {1,3}
    # instead of {0,1}, verify same numeric value via a direct (slower) general-subset version.
    def W_general(A, t):
        r = len(A)
        base_exp = {a: 1 for a in A}
        coeff0 = math.factorial(r)
        prop_s_terms = []
        e = dict(base_exp)
        e['D'] = e.get('D', 0) + 1
        prop_s_terms.append((Fraction(coeff0), e))
        for b in A:
            e2 = dict(base_exp)
            e2[b] = e2.get(b, 0) + 1
            prop_s_terms.append((Fraction(coeff0), e2))
        varlist = ['D'] + list(A)
        nv = len(varlist)

        def compositions(total_, parts):
            if parts == 1:
                yield (total_,)
                return
            for i in range(total_ + 1):
                for rest in compositions(total_ - i, parts - 1):
                    yield (i,) + rest

        moment_terms = []
        for comp in compositions(t, nv):
            k_D = comp[0]
            ks = comp[1:]
            multinom_coeff = math.factorial(t)
            multinom_coeff //= math.factorial(k_D)
            for k in ks:
                multinom_coeff //= math.factorial(k)
            c = Fraction(multinom_coeff)
            for k in ks:
                c /= (k + 1)
            e = {}
            if k_D:
                e['D'] = k_D
            for a, k in zip(A, ks):
                if k:
                    e[a] = k
            moment_terms.append((c, e))

        total = Fraction(0)
        for c1, e1 in prop_s_terms:
            for c2, e2 in moment_terms:
                combined = defaultdict(int)
                for v, p in e1.items():
                    combined[v] += p
                for v, p in e2.items():
                    combined[v] += p
                prod_fact = 1
                for k in combined.values():
                    prod_fact *= math.factorial(k)
                total += c1 * c2 * prod_fact
        return total

    tests = [((1, 3), 2), ((2, 4, 0), 3), ((4,), 1), ((0, 1, 2, 3), 2)]
    all_ok3 = True
    for A, t in tests:
        r = len(A)
        w_prefix = W(r, t)
        w_general = W_general(A, t)
        ok = (w_prefix == w_general)
        all_ok3 = all_ok3 and ok
        print(f"A={A} (r={r}) t={t}  W(prefix subset)={w_prefix}  W(this subset)={w_general}  match={ok}")
    print("SYMMETRY-IN-SUBSET-CHOICE CHECKS MATCH:", all_ok3)
